version: "3"
services:
  rabbitmq-container:
    image: rabbitmq:3.9.11-management-alpine
    hostname: rabbitmq-container
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - "TZ=@timezone@"
    networks:
      - resolute

  app-container:
    image: cloudpay/wezaam-challenge
    ports:
      #  local : container expose
      - "8080:7070"
    environment:
      - spring_rabbitmq_host=rabbitmq-container
      - spring_rabbitmq_port=5672
      - spring_rabbitmq_username=guest
      - spring_rabbitmq_password=guest
      - spring_profiles_active=docker
      
    networks:
      - resolute
    depends_on:
      - rabbitmq-container


networks:
  resolute:
    external:
      name: resolute
